### ISSUE TITLE
Feat: Refine the documentation layout in an intuitive manner

### ISSUE THREAD

**Issue by Yangyang96** [KusionStack/kusion#1218] opened 2024-07-15 07:41 UTC
### What would you like to be added?

- [ ] Separate content for app developers and platform engineers to reduce the learning curve.
- [ ] Organize content and layout in a way that is easy to follow.

### Why is this needed?

To enable better user engagement.

**Comment by ffforest** [comment] 2024-12-24 06:29
Dupe of #1222. Closing.

**Closed by ffforest** 2024-12-24 06:29 UTC
Labels: kind/documentation
