### ISSUE TITLE
Feat: Refine the concept part of the documentation to maintain brevity and precision 

### ISSUE THREAD

**Issue by Yangyang96** [KusionStack/kusion#1217] opened 2024-07-15 07:15 UTC
### What would you like to be added?

- [ ] Eliminate extraneous details to focus on the main concept.

- [ ] Add an outline to the content structure to make it easier to understand, a resource relationship diagram will be a plus.

### Why is this needed?

To help improve user experience.

**Comment by ffforest** [comment] 2024-12-24 06:28
Dupe of #1221. Closing

**Closed by ffforest** 2024-12-24 06:28 UTC
Labels: kind/documentation
